#!/usr/bin/python3


def FrequentWords(text, k, t):
    n = len(text)-k+1
    words = {}
    for i in range(n):
        words[text[i:i+k]] = words.get(text[i:i+k], 0)
        words[text[i:i+k]] += 1

    max_value = max(words.values())
    out = []
    if(max_value >= t):
        print(max_value)
        out = [k for k, v in words.items() if(v == max_value)]
    return out


def clump_finding(g, k, l, t):
    n = len(g) - l + 1
    out = []
    for i in range(n):
        clump = g[i:i+l]
        words = FrequentWords(clump, k, t)
        for j in range(len(words)):
            out.append(words[j])

    return out


out = clump_finding("AACAGCTATATGGTTTCAAGTCTCTGTGTTTGACTATGGGCGCCCACCTTCTTACACCCTGAGTTGGCGCTATTCTTCCGCTGCACGCTATGCTATGCACGCTATATTACTCAAGCTAACACTCAAGACTCAAGCTATAGTATATCACCCGTAGAGACGGTCCACTACCGCACCCGCCGCACGGTCACGGTCGTCGTTGCTCCGGGCTATATACTCATAACATACTCATACTCATAAAATATCCTCGAGTATCATCATAATCTGAAGAAAGCCCTTGTGCCGAGCAGACTGGGACGCATCGTTATAATCCGCTCCGGTGTCGTCTTGTTCCGCTCCGCTTGACCGCTTGACCACCCTCGAGTCGTGTAAACTTGCTCGGGATTGTCCCCGATGTGTTTATGCACGATCAGACTGAGAAGCTACCGTGATTCCGACAGAGATCAATCTTTAAAGGAACGAATACGAAAATCTGGTGAGAGATATGTTGACTACGATACATATTTAGGGATCAGAGGAGGAGTGCATCATCAAGGAGTGCATCCGGGCGTCGCTAAATAGAAGGGGAGCACACCTACAAATCGCGAGGTTCATGCACAACCTGTGCTCTGTACTGTCCCTCTCGAAAAACTAAGCTAGCCGTACTTGAGTCCTCCTTGCCTACGCTCGTAAAGAATCAGTTCTTCCTCAGTCGTTAGGTGTCCATAAAAAGAGTCATACACTTCCTTGTGCTTAATCGAAAATTGGGAATTGCACTATTCTAAGCATCTAATAATGGTGGATTACTTGTAGTTAGCGCCAGCCTCCTTTCCCTTTCTATCTATCCTTGTTTTATATGTCTTATATTATATGTCAGTCATGCCGTTCTGGCTCATGTCTGAAATTATCGAACTAGCACTCGGATCGATGTGTTACCAAAGGTGTACTCGTTGGGTAGGTAAGAGATCAACCAAATCTATATGGCACGTTGCCCTGGTAGAAAGCCACCGGAGAAGAGTCCAGCCCATCAACCAGGAACTCTGACGTATCTTCGTGGCAAGTACGTGCTGGCTCTCGGGGAAGGGTCTATTTTCGGCTGGGCGGCTTCCGAGGTAAATGGACCTCATCAACTGCTTACCCGGCTCCGCCCATAGTCTCTTCTGGTCTATGTTTTTGATGAACCCCGTTGTCCAGCACATTATTTGTTTGTTAATCTCTTGTTAATCTTCTTGTGCCTAATGAGAGAGCGCTCTTGCCTACCCTAGGCGGCTATATTCCCAACTCCAGTGTTTCAATGCCGCTTCGAAATGATAAGGATGTAAGCACTAACACGGGTGTTTGTGGGTCTTGGGGAAGTTCACCGTCTTCTTCATTCACCGTCTCTCATGCTAGATACATCGTACTTCCCACAAGATCACGCGCTTCCTCCTCAATCCGAGGCGACAGGCGTGTCACTTCGGTCGCACGTGTCTTCGTAAATTTTTTCGACTCCTTTTGCTTTTGCTTTGCTTTTGCTCTGTATTGTGAAAGGTCCGTACTCATTAAGCACTGGTGTGAACAGCTAAGAGTAGAAGTGTATACTCTTCTGAATTCCACTATATAGAGTCTGGGATGAGTCTGGGAAGTTCTCCCAGACAACCAGACAACAAACTAATAAGCTGCCATTATGTGCGCCGGGAGCTGGGGTTTCCGCTTCACTGGTGATTAAATAACGTAAACCTGCCGCGCGCGGCTGATAAGTATAGTGCAAATGGCGTTCCTTACCACACGATTTTCGATTTTGTTCCACTCGAGGCGTTGAGACTTCACGAGTCAATACTGGTCCTTCTCTACCGGAGTACGCGGGAGTACGTGACGTCTTAACTCGAACCTAATGCGTTGCGAGCCGGACCCAACGTATAACGTATGACTATGACCCTCAAGCGCAGCCGTGGCAAAAGCTTCACACCACTAATCTGGGCTACTAGATCTCCACTACTAGATCCA", 10, 27, 3)


for i in range(len(out)):
    print(out[i])
