#!/usr/bin/python3

import operator


def FrequentWords(text, k):
    n = len(text)-k+1
    words = {}
    for i in range(n):
        words[text[i:i+k]] = words.get(text[i:i+k], 0)
        words[text[i:i+k]] += 1

    max_value = max(words.values())
    out = [k for k, v in words.items() if v == max_value]

    return out


print(FrequentWords("GGCGTTTTCCATGCACCCATGCACGTTGCCTCCGTTGCCTCCAAATGAGCGGGCGTTTTGGCGTTTTGGCGTTTTGGCGTTTTGTTGGAAGGCGTTTTGGCGTTTTAAATGAGCGGTTGGAACCATGCACGTTGCCTCCGGCGTTTTGTTGGAAGGCGTTTTGTTGGAAGGCGTTTTGTTGGAAAAATGAGCGGTTGCCTCCCCATGCACGTTGCCTCCAAATGAGCGGGCGTTTTGTTGGAAAAATGAGCGGTTGGAAGTTGCCTCCGGCGTTTTGTTGCCTCCGTTGGAAGTTGCCTCCCCATGCACGTTGCCTCCGTTGCCTCCGTTGCCTCCGGCGTTTTAAATGAGCGCCATGCACCCATGCACGTTGGAACCATGCACGTTGGAAGTTGCCTCCGGCGTTTTGTTGGAAGTTGCCTCCAAATGAGCGAAATGAGCGGGCGTTTTGGCGTTTTCCATGCACGGCGTTTTCCATGCACGTTGCCTCCGTTGGAAGGCGTTTTAAATGAGCGCCATGCACGTTGCCTCCGTTGCCTCCGTTGCCTCCGTTGCCTCCAAATGAGCGGGCGTTTTGTTGGAAGTTGGAACCATGCACCCATGCACGTTGCCTCCGTTGCCTCCCCATGCACGTTGGAACCATGCACCCATGCACAAATGAGCGGGCGTTTTAAATGAGCGGTTGCCTCCGTTGGAAGTTGGAAGTTGCCTCCGTTGGAAGTTGCCTCCGTTGGAAGTTGGAACCATGCACGGCGTTTTGGCGTTTTAAATGAGCGCCATGCACAAATGAGCGGTTGCCTCCGTTGGAACCATGCACCCATGCACAAATGAGCGGTTGCCTCCAAATGAGCGCCATGCACAAATGAGCGGTTGGAA", 11))
